name = "senor-shabi-api"
main = "server/src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[pages_build_output_dir = "dist/client"]

[env.production]
vars = { ENVIRONMENT = "production" }

[env.preview]
vars = { ENVIRONMENT = "preview" }

[[d1_databases]]
binding = "senor_shabi_db"
database_name = "senor-shabi-db"
database_id = "e932169c-2609-44f5-9478-547d7b95c946"
